"""Style targets. Difference is material + light + micro-geometry, not one mesh and four shaders.

Micro-geometry flags are consumed by the Blender renderer:
- bubbles: interior spheres (gummy)
- lumps: low-frequency sculpt dents (clay)
- fur: short surface pile shells (plush)
- seam: stitched cord on primary volumes (plush)
"""
from __future__ import annotations

STYLES = {
    "gummy": {
        "thickness_mul": 1.28,
        "inflate_mul": 1.2,
        "radius_mul": 1.18,
        "roughness": 0.12,
        "metallic": 0.0,
        "transmission": 0.62,
        "ior": 1.42,
        "subsurface": 0.32,
        "sss_scale": 0.06,
        "sss_radius": (1.0, 0.35, 0.25),
        "specular": 0.55,
        "coat": 0.25,
        "coat_roughness": 0.08,
        "sheen": 0.0,
        "sheen_roughness": 0.4,
        "saturation": 1.18,
        "value": 1.06,
        "toward": None,
        "toward_amt": 0.0,
        "bubbles": True,
        "lumps": False,
        "fur": False,
        "seam": False,
        "bevel_mul": 1.15,
        "key": {"energy": 42, "size": 1.15, "color": (1.0, 0.97, 0.94)},
        "fill": {"energy": 10, "size": 1.6, "color": (0.9, 0.95, 1.0)},
        "rim": {"energy": 22, "size": 0.7, "color": (1.0, 0.82, 0.65)},
        "world": 0.035,
        "exposure": -0.05,
        "gtao": 0.35,
    },
    "clay": {
        "thickness_mul": 1.05,
        "inflate_mul": 0.85,
        "radius_mul": 1.0,
        "roughness": 0.78,
        "metallic": 0.0,
        "transmission": 0.0,
        "ior": 1.45,
        "subsurface": 0.08,
        "sss_scale": 0.02,
        "sss_radius": (1.0, 0.85, 0.7),
        "specular": 0.18,
        "coat": 0.0,
        "coat_roughness": 0.4,
        "sheen": 0.02,
        "sheen_roughness": 0.6,
        "saturation": 0.78,
        "value": 0.98,
        "toward": (0.78, 0.62, 0.48),
        "toward_amt": 0.14,
        "bubbles": False,
        "lumps": True,
        "fur": False,
        "seam": False,
        "bevel_mul": 1.0,
        "key": {"energy": 64, "size": 1.7, "color": (1.0, 0.97, 0.93)},
        "fill": {"energy": 10, "size": 2.2, "color": (0.95, 0.95, 1.0)},
        "rim": {"energy": 6, "size": 1.2, "color": (1.0, 0.95, 0.9)},
        "world": 0.07,
        "exposure": 0.15,
        "gtao": 0.85,
    },
    "plush": {
        "thickness_mul": 1.22,
        "inflate_mul": 1.15,
        "radius_mul": 1.4,
        "roughness": 0.92,
        "metallic": 0.0,
        "transmission": 0.0,
        "ior": 1.4,
        "subsurface": 0.04,
        "sss_scale": 0.01,
        "sss_radius": (1.0, 0.9, 0.85),
        "specular": 0.12,
        "coat": 0.0,
        "coat_roughness": 0.5,
        "sheen": 0.72,
        "sheen_roughness": 0.55,
        "saturation": 0.9,
        "value": 1.08,
        "toward": (0.96, 0.93, 0.9),
        "toward_amt": 0.1,
        "bubbles": False,
        "lumps": False,
        "fur": True,
        "seam": True,
        "bevel_mul": 1.35,
        "key": {"energy": 48, "size": 2.8, "color": (1.0, 0.97, 0.94)},
        "fill": {"energy": 28, "size": 3.2, "color": (1.0, 0.98, 0.96)},
        "rim": {"energy": 18, "size": 1.6, "color": (1.0, 0.94, 0.9)},
        "world": 0.22,
        "exposure": 0.2,
        "gtao": 1.0,
    },
    "glossy": {
        "thickness_mul": 0.92,
        "inflate_mul": 0.55,
        "radius_mul": 0.88,
        "roughness": 0.06,
        "metallic": 0.0,
        "transmission": 0.0,
        "ior": 1.48,
        "subsurface": 0.0,
        "sss_scale": 0.0,
        "sss_radius": (1.0, 1.0, 1.0),
        "specular": 0.62,
        "coat": 1.0,
        "coat_roughness": 0.03,
        "sheen": 0.0,
        "sheen_roughness": 0.3,
        "saturation": 1.08,
        "value": 1.0,
        "toward": None,
        "toward_amt": 0.0,
        "bubbles": False,
        "lumps": False,
        "fur": False,
        "seam": False,
        "bevel_mul": 0.7,
        "key": {"energy": 70, "size": 0.28, "color": (1.0, 1.0, 1.0)},
        "fill": {"energy": 10, "size": 1.4, "color": (0.9, 0.93, 1.0)},
        "rim": {"energy": 90, "size": 0.22, "color": (0.85, 0.92, 1.0)},
        "world": 0.03,
        "exposure": 0.25,
        "gtao": 0.25,
    },
}

# Different framing per subject. Not one camera for the set.
CAMERAS = {
    "heart": {"yaw_deg": 10, "pitch_deg": 14, "lens_mm": 78, "margin": 1.34},
    "rocket": {"yaw_deg": -18, "pitch_deg": 7, "lens_mm": 62, "margin": 1.26},
    "teddy": {"yaw_deg": 14, "pitch_deg": 16, "lens_mm": 68, "margin": 1.3},
    "plant": {"yaw_deg": 20, "pitch_deg": 8, "lens_mm": 58, "margin": 1.28},
    "rose": {"yaw_deg": -12, "pitch_deg": 10, "lens_mm": 72, "margin": 1.72},
    "messy": {"yaw_deg": 0, "pitch_deg": 2, "lens_mm": 92, "margin": 1.42},
}

STYLE_ORDER = ("gummy", "clay", "plush", "glossy")
